#!/bin/sh

#
# Simple script to generate ES256 ECDSA private key and corresponding public key. 
# They are identical to ones generated by AppStoreConnect (private key is named like 'AuthKey_XXXXXX.p8').
#

set -euo pipefail
# set -x

echo "Generating private key file 'ec_private.pem'"
openssl ecparam -genkey -name prime256v1 -noout -out ec_private.pem
cat ec_private.pem

echo
echo "Generating public key file 'ec_public.pem'"
openssl ec -in ec_private.pem -pubout -out ec_public.pem
cat ec_public.pem
